### ISSUE TITLE
Wonderful Badge View

### ISSUE THREAD

**Issue by cc1rr** [bingoogolapple/BGABadgeView-Android#1]
1,showCriclePointBadge 应该是笔误 showCirclePointBadge.
2,请教一下为什么要使用AppCompatCheckedTextView、AppCompatTextView、AppCompatRadioButton而不用CheckedTextView、TextView、RadioButton减少依赖？

**Comment by bingoogolapple** [comment]
笔误！ 兼容低版本，而且现在项目基本都有用到appcompt-v7中的AppCompatActivity，相当于也没添加多的依赖
