### ISSUE TITLE
getNavigationBarHeight 的疑问

### ISSUE THREAD

**Issue by TomeOkin** [bingoogolapple/BGABadgeView-Android#14]
BGABadgeViewUtil 的 getNavigationBarHeight 里怎么写的是`resources.getIdentifier("status_bar_height", "dimen", "android");`，而内部调用的`checkDeviceHasNavigationBar` 里却检查的是 `rs.getIdentifier("config_showNavigationBar", "bool", "android")`。
第一个应该是`navigation_bar_height`吧？

getNewStartY 里为什么不直接使用 getHeight，如果要手动计算可绘制高度，除了要减去状态栏的高度外，还要减去标题栏的高度（toolbar、custom toolbar...），标题栏高度这个不好处理。

**Comment by bingoogolapple** [comment]
@TomeOkin 谢谢反馈
