### ISSUE TITLE
radiobutton 没有效果

### ISSUE THREAD

**Issue by igeek-YZ** [bingoogolapple/BGABadgeView-Android#18]
我是使用的过程中发现BGABadgeRadioButton没有显示任何形式的提示。。。。

**Comment by bingoogolapple** [comment]
@igeek-YZ 我demo里的radiobutton在你手机上显示正常不？

**Comment by bingoogolapple** [comment]
@igeek-YZ 你那边这个问题解决了没？

我 demo 里点击底部 BGABadgeRadioButton 切换 tab 并没有切换上面的内容，只是在界面顶部弹了吐司来提示点击了某个 tag，以表明 BGABadgeRadioButton 和原生的 RadioGroup 结合使用时并没有事件冲突

**Comment by missAllen** [comment]
我的radiobutton也没有效果

**Comment by bingoogolapple** [comment]
demo 的 activity_main.xml 中就是用的 RadioButton，用最新版 v1.1.5 试试

gradle 配置有变动，看下最新的 README 和 demo
