### ISSUE TITLE
小米4  android 6.0.1 没有效果

### ISSUE THREAD

**Issue by liaoinstan** [bingoogolapple/BGABadgeView-Android#30]
按下的时候badge消失了，松开又出现或者消失，拖拽 过程中没有任何动画

**Comment by liaoinstan** [comment]
知道了，作者用的是悬浮控件，6.0+系统的很多手机默认是关闭悬浮窗的（小米、华为、魅族等’），所以显示一片空白。

**Comment by Jameshuihui** [comment]
怎么解决这个问题呢

**Comment by rongdongliu** [comment]
悬浮控件,这个问题，我的小米2a，5.1.1也需要手动去安全中心开启权限，但是，一般的手机用户，压根不知道怎么去打开，希望楼主想一个折衷的方法呀

**Comment by tpnet** [comment]
没办法的，所以作者不维护了。已经放弃了。

**Comment by bingoogolapple** [comment]
用最新版 v1.1.5，gradle 配置有变动，看下最新的 README 和 demo
