### ISSUE TITLE
最新

### ISSUE THREAD

**Issue by yigepang** [bingoogolapple/BGABadgeView-Android#39]
android studio 3.0中，26 版本编译出现以下错误。

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve cn.bingoogolapple:bga-badgeview:1.1.3.

Could not resolve cn.bingoogolapple:bga-badgeview:1.1.3.
Required by:
    project :app
 > Could not resolve cn.bingoogolapple:bga-badgeview:1.1.3.
    > Could not get resource 'https://www.jitpack.io/cn/bingoogolapple/bga-badgeview/1.1.3/bga-badgeview-1.1.3.pom'.
          > Could not HEAD 'https://www.jitpack.io/cn/bingoogolapple/bga-badgeview/1.1.3/bga-badgeview-1.1.3.pom'. Received status code 401 from server: Unauthorized

**Comment by Jonnylee0012** [comment]
hi，有解决吗？

**Comment by bingoogolapple** [comment]
升级到最新版

v1.1.5，用法有变动，看下 README 和 demo
