### ISSUE TITLE
为什么RadioGroup的监听没效果？

### ISSUE THREAD

**Issue by merhong2012** [bingoogolapple/BGABadgeView-Android#4]
代码： 
 main_bottom.setOnCheckedChangeListener(tabCheckedListener);
 RadioGroup.OnCheckedChangeListener tabCheckedListener = new RadioGroup.OnCheckedChangeListener() {
        @Override
        public void onCheckedChanged(RadioGroup radioGroup, int i) {
            ((BGABadgeRadioButton) main_bottom.getChildAt(i)).setChecked(true);
            viewPager.setCurrentItem(i,false);
        }
    };
里面的BGABadgeRadioButton 点击没反应

**Comment by Calamus-Cajan** [comment]
http://blog.csdn.net/cuiran/article/details/45065477

**Comment by bingoogolapple** [comment]
@merhong2012  方便把加了BGABadgeView-Android后RadioButton点击没反应的demo发我邮箱吗  bingoogolapple@gmail.com

或者加qq群
![BGA_CODE_CLUB](http://7xk9dj.com1.z0.glb.clouddn.com/BGA_CODE_CLUB.png?imageView2/2/w/200)
