### ISSUE TITLE
重新放回时曲线不能绘制

### ISSUE THREAD

**Issue by yhsj0919** [bingoogolapple/BGABadgeView-Android#5]
拖拽徽章，当线断裂，再次放回到半径之内，曲线不能重新绘制

 // 处理断开事件
            if (BGABadgeViewUtil.getDistanceBetween2Points(mDragCenter, mStickCenter) > mDismissThreshold) {
                mDismissAble = true;
                postInvalidate();
            } else {
                mDismissAble = false;
            }

在这里加上else体验会更好

**Comment by bingoogolapple** [comment]
本来是加上了的，看qq消息列表再次放回到半径之内时，也没有重新绘制，就又取消了

**Comment by yhsj0919** [comment]
还有就是在某些手机上，（安卓4.2.2？）因为改系统的问题导致获取不到状态栏，而绘制时强制剪掉状态栏高度产生绘制偏移
