### ISSUE TITLE
JCenter库服务要停止了，您有计划迁移到其他的库服务上吗？

### ISSUE THREAD

**Issue by norman19882003** [bingoogolapple/BGABadgeView-Android#67]
JCenter库服务要停止了，您有计划迁移到其他的库服务上吗？

**Comment by bingoogolapple** [comment]
不用迁移，直接用 jitpack 就行

https://jitpack.io/#bingoogolapple/BGABadgeView-Android

**Comment by bingoogolapple** [comment]
该库已迁移到 JitPack，请查看最新使用文档。其他 BGA 系列开源库后续也会陆续迁移到 JitPack
